### ISSUE TITLE
Login/Singup Design

### ISSUE THREAD

**Issue by OkenHaha** [OkenHaha/react-blog#11]
On the Website the design for the Login and Registration modal doesn't have a proper design look.
![image](https://github.com/user-attachments/assets/6e2a017d-ca8d-4cf4-88e0-faa889c5de34)
![image](https://github.com/user-attachments/assets/ac98a269-62e9-4ed6-b5a1-877ea28100f7)
Try to add some desing for this modal by following a basic desgin structure by following the color structure of the blog

**Comment by varruunnn** [comment]
I have reviewed the Login and Registration modal design on the website, and I noticed it could benefit from some enhancements to improve its visual appeal and consistency with the overall blog design.
I would like to take up the task of updating the modal's design by aligning it with the blog’s colour scheme and design principles, ensuring a cleaner and more cohesive user experience.
Please assign me this task

**Comment by OkenHaha** [comment]
@varruunnn I'm assigning it to you. Please provide a screenshot of your work when making the pull request. Thanks
